/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.progtech;

/**
 *
 * @author Adam
 */
public class CompletePCs extends javax.swing.JFrame {
    
    Logger logger = Logger.getInstance();
    
    


    /**
     * Creates new form CompletePCs
     */
    public CompletePCs() {
        initComponents();
    }
    
    public AComputer acomp;
    
        MinositesGyar minositoG = new MinositesGamer();
        MinositesGyar minositoO = new MinositesOffice();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(600, 200));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Complete PC's");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz egyet", "Gyenge gamer", "Közepes gamer", "Hardcore gamer", "Gamer legenda", "Átlag felhasználó" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText(" ");

        jLabel3.setText("Az általad választott számítógép specifikációja:");

        jLabel4.setText("Választható extrák");

        jButton1.setText("Ok");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válassz egyet", "RGB", "Külső DVD író" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(237, 237, 237))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(215, 215, 215))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(jLabel4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))
                        .addGap(0, 172, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jLabel2.setText(acomp.print().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if (evt.getStateChange() == evt.SELECTED)
        if (jComboBox1.getSelectedIndex() == 0){
        }
        if (jComboBox1.getSelectedIndex()== 1){
            acomp = new Computer("Intel","HyperX",8,"nVidia GTX 1060","SSD",6,"Crosshair",600,"Cougar","ASUS","CoolerMaster",300000);
        }
        if (jComboBox1.getSelectedIndex() == 2){
             acomp = new Computer("AMD","HyperX",16,"nVidia GTX 1660","SSD",6,"Crosshair",600,"Cougar","ASUS","CoolerMaster",400000);
        }
        if (jComboBox1.getSelectedIndex() == 3){
             acomp = new Computer("INTEL","HyperX",24,"nVidia GTX 1660","SSD",16,"Crosshair",650,"Cougar","ASUS","CoolerMaster",500000);
        }
        if (jComboBox1.getSelectedIndex() == 4){
             acomp = new Computer("INTEL","HyperX",24,"nVidia GTX 1660","SSD",16,"Crosshair",650,"Cougar","ASUS","CoolerMaster",500000);
        }if (jComboBox1.getSelectedIndex() == 5){
             acomp = new Computer("INTEL","HyperX",4,"nVidia GTX 1050","SSD",8,"Crosshair",450,"Cougar","ASUS","CoolerMaster",150000);
        }
        jLabel2.setText(acomp.print().toString());
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
         if (evt.getStateChange() == evt.SELECTED){
        if (jComboBox2.getSelectedIndex() == 0){
        }
        if (jComboBox2.getSelectedIndex()== 1){
             Minosites minosites = minositoG.Create();
            acomp = minosites.Minosit(acomp);
        }
        if (jComboBox2.getSelectedIndex() == 2){
             Minosites minosites = minositoO.Create();
            acomp = minosites.Minosit(acomp);
        }
        jLabel2.setText(acomp.print().toString());
       }else if (evt.getStateChange() == evt.DESELECTED){
           if (jComboBox1.getSelectedIndex() == 0){
        }
        if (jComboBox1.getSelectedIndex()== 1){
            acomp = new Computer("Intel","HyperX",8,"nVidia GTX 1060","SSD",6,"Crosshair",600,"Cougar","ASUS","CoolerMaster",300000);
        }
        if (jComboBox1.getSelectedIndex() == 2){
             acomp = new Computer("AMD","HyperX",16,"nVidia GTX 1660","SSD",6,"Crosshair",600,"Cougar","ASUS","CoolerMaster",400000);
        }
        if (jComboBox1.getSelectedIndex() == 3){
             acomp = new Computer("INTEL","HyperX",24,"nVidia GTX 1660","SSD",16,"Crosshair",650,"Cougar","ASUS","CoolerMaster",500000);
        }
        if (jComboBox1.getSelectedIndex() == 4){
             acomp = new Computer("INTEL","HyperX",24,"nVidia GTX 1660","SSD",16,"Crosshair",650,"Cougar","ASUS","CoolerMaster",500000);
        }if (jComboBox1.getSelectedIndex() == 5){
             acomp = new Computer("INTEL","HyperX",4,"nVidia GTX 1050","SSD",8,"Crosshair",450,"Cougar","ASUS","CoolerMaster",150000);
        }
        jLabel2.setText(acomp.print().toString());
        }
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String pc = String.valueOf(jComboBox1.getSelectedItem());
        String extra = String.valueOf(jComboBox2.getSelectedItem());
        if (jComboBox2.getSelectedIndex() != 0){
           logger.complete(pc,extra);
        } else 
        logger.complete(pc,"nincs");
        
        
        
        
        OrderFrame ordersData = new OrderFrame();
        ordersData.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletePCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletePCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletePCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletePCs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompletePCs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
